env:
  cypress/globals: true
  browser: true
  commonjs: true
  es2020: true
  mocha: true
  node: true
extends: "eslint:recommended"
parserOptions:
  ecmaVersion: 11
  sourceType: "module"
rules: {
  "quotes": ["error", "single"],
  "semi": ["error", "always"]
}
plugins: ["eslint-plugin-cypress"]
